In [1]:
import tensorflow as tf

/Users/toanpv/tensorflow_tutorial/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)


In [2]:
# In tensorflow version
tf.__version__

'1.9.0'

# Introduction about Tensorflow

## Constant

Là các đại lượng không thay đổi trong quá trình chạy chương trình

In [9]:
x1 = tf.constant(1, name='const_x1')

print(x1)

x2 = tf.constant(2.)

print(x2)

x3 = tf.constant(3, dtype='float32')

print(x3)

Tensor("const_x1_3:0", shape=(), dtype=int32)
Tensor("Const_9:0", shape=(), dtype=float32)
Tensor("Const_10:0", shape=(), dtype=float32)


In [10]:
v1 = tf.constant([1, 2, 3], dtype=tf.float32, name='v1_const_vector')
print(v1)

Tensor("v1_const_vector:0", shape=(3,), dtype=float32)


In [11]:
sess = tf.Session()

In [15]:
sess.run(v1)

array([1., 2., 3.], dtype=float32)

**Note** tensor có thể là một số thực, số nguyên, chuỗi, ma trận 1D, 2D, 3D... mutil-demension matrix

In [16]:
# Create tensor 2D

v2 = tf.constant([
    [1, 2, 3],
    [3, 4, 5]
], dtype=tf.float32, name='2d_matrix')

In [17]:
sess.run(v2)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

In [20]:
v2.eval(session=sess)

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

## Perform operators

In [23]:
# Add x1 + x2

y1 = x2 + x3

print(y1)

Tensor("add_2:0", shape=(), dtype=float32)


**Note** khi xử lý trên tensor thì phải cùng dtype

In [24]:
sess.run(y1)

5.0

In [25]:
v3 = tf.constant([
    [1, 1, 1],
    [3, 3, 2]
], dtype=tf.float32, name='2d_matrix')

In [26]:
y2 = v2 + v3

In [27]:
sess.run(y2)

array([[2., 3., 4.],
       [6., 7., 7.]], dtype=float32)

## Placeholder

### Create
Placeholder sử dụng trong trường hợp chúng ta cần load dữ liệu đầu vào

In [28]:
p1 = tf.placeholder(dtype=tf.float32)
p2 = tf.placeholder(dtype=tf.float32)

In [29]:
# Asign operation for placeholder

o_add = p1 + p2
o_mul = p1 * p2
o_delta = p1**2 + p2

In [30]:
print(o_add)

Tensor("add_4:0", dtype=float32)


## Feed value for placeholder


In [32]:
d_values = {
    p1 : 20,
    p2 : 10
}

sess.run(o_delta, feed_dict=d_values)

410.0

In [33]:
sess.run([o_add, o_mul, o_delta], feed_dict=d_values)

[30.0, 200.0, 410.0]

## Variables

### Create

In [34]:
var_1 = tf.Variable(name='var_1', initial_value=10)
var_2 = tf.Variable(name='var_2', initial_value=50)

**Note** cần phải khởi tạo biến trước khi đưa vào tính toán trên session

In [36]:
sess.run(var_1.initializer)

In [37]:
sess.run(var_1)

10

In [39]:
tf.global_variables_initializer().run(session=sess)

In [40]:
sess.run(var_2)

50